[package]
name = "honfoglalo_classic_server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.5", features = ["macros", "query"] }
axum-extra = { version = "0.9.3", features = ["typed-header"] }
anyhow = "1.0.86"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-aux = "4.5.0"
serde_with = "3.9.0"
quick-xml = { version = "0.36.1", features = ["serialize"] }
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread", "signal"] }
async-trait = "0.1.80"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
tracing = "0.1.40"
surrealdb = { version = "1.5.4", features = ["kv-mem"] }
chrono = "0.4.38"
dotenvy = "0.15.7"
headers = "0.4.0"
time = "0.3.36"
hex = "0.4.3"

[dev-dependencies]
serde_test = "1"
