style_edition = "2024"
edition = "2024"
indent_style = "Block"
reorder_imports = true
brace_style = "SameLineWhere"
newline_style = "Native"
hard_tabs = true
tab_spaces = 4
group_imports = "StdExternalCrate"

wrap_comments = true
comment_width = 100
format_code_in_doc_comments = true
normalize_comments = true
